version: '3.8'
services:
  # בסיסי נתונים - רק לפיתוח
  dev-postgres:
    image: postgres:15
    container_name: dev-postgres
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"  # פורט שונה כדי להימנע מהתנגשויות
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  dev-neo4j:
    image: neo4j:latest
    container_name: dev-neo4j
    environment:
      NEO4J_AUTH: neo4j/devpassword
    ports:
      - "7475:7474"  # פורט שונה
      - "7688:7687"  # פורט שונה
    volumes:
      - dev_neo4j_data:/data
    networks:
      - dev-network

  # שירותי פיתוח
  dev-java-backend:
    build: 
      context: ./java-project
      dockerfile: Dockerfile
    container_name: dev-java-app
    ports:
      - "8081:8080"  # פורט שונה
    depends_on:
      - dev-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dev-postgres:5432/devdb
      - SPRING_DATASOURCE_USERNAME=devuser
      - SPRING_DATASOURCE_PASSWORD=devpass
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - dev-network
    volumes:
      - ./java-project:/app
      - /app/target

  dev-python-backend:
    build:
      context: ./python-project
      dockerfile: Dockerfile
    container_name: dev-python-app
    ports:
      - "5001:5000"  # פורט שונה
    depends_on:
      - dev-neo4j
    environment:
      - NEO4J_URI=bolt://dev-neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=devpassword
      - ENV=development
    networks:
      - dev-network
    volumes:
      - ./python-project:/app

  dev-react-frontend:
    build:
      context: ./react-project
      dockerfile: Dockerfile
    container_name: dev-react-app
    ports:
      - "3001:3000"  # פורט שונה
    volumes:
      - ./react-project:/app
      - /app/node_modules
    networks:
      - dev-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8081

volumes:
  dev_postgres_data:
  dev_neo4j_data:

networks:
  dev-network:
    driver: bridge